version: '3.8'

services:
  web:
    build: .
    ports:
      - "5158:5158"
      - "443:443"
    volumes:
      - "./SpotifyAPI/Data"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Spotify;Username=postgres;Password=123456
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: Spotify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
